version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    entrypoint: ["sh", "/app/entrypoints/wait-for-db.sh"]
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn personal_portfolio.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: 1
      SECRET_KEY: your_secret_key_here
      ALLOWED_HOSTS: '*'
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: mydb
      DB_USER: myuser        
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
