# Remove the version attribute as it is obsolete
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    entrypoint: ["sh", "/app/entrypoints/wait-for-db.sh"]
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn personal_portfolio.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: 1
      SECRET_KEY: your_secret_key_here
      ALLOWED_HOSTS: '*'
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - app-network

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticfiles:/srv/static
      - ./media:/srv/media
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
