services:
  db:
    image: postgres:13
    restart: always
    # Use variables from the .env file for security
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    image: ${IMAGE_NAME}:latest
    entrypoint: ["sh", "/app/entrypoints/wait-for-db.sh"]
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn personal_portfolio.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      # Mount the shared volume where static files will be collected
      - staticfiles_volume:/app/staticfiles
      # Mount the shared volume for user-uploaded media files
      - media_volume:/app/media
    # Load all environment variables from the .env file
    env_file:
      - ./.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_ENGINE=${DOCKER_DB_ENGINE}
      - DB_NAME=${DOCKER_DB_NAME}
      - DB_USER=${DOCKER_DB_USER}
      - DB_PASSWORD=${DOCKER_DB_PASSWORD}
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_PORT=${DOCKER_DB_PORT}
    depends_on:
      - db
    networks:
      - app-network

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # Mount the same shared volume to serve static files
      - staticfiles_volume:/srv/static
      # Mount the same shared volume to serve media files
      - media_volume:/srv/media
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Define the named volumes that will be shared between containers
volumes:
  postgres_data:
  staticfiles_volume: # For static files (CSS, JS)
  media_volume:     # For media files (user uploads)
  caddy_data:
  caddy_config:
