[project]
name = "my-django-portfolio"
version = "0.2.0"
description = "My portfolio website, created using Django/TailwindCSS"
requires-python = ">=3.13"
dependencies = [
    "asgiref==3.8.1",
    "bleach==6.2.0",
    "dj-database-url==2.3.0",
    "django==5.1.7",
    "django-ckeditor==6.7.2",
    "django-environ==0.12.0",
    "django-js-asset==3.1.2",
    "django-summernote==0.8.20.0",
    "django-tinymce==4.1.0",
    "gunicorn==23.0.0",
    "packaging==25.0",
    "pillow==11.1.0",
    "psycopg2-binary==2.9.10",
    "sqlparse==0.5.3",
    "typing-extensions==4.13.2",
    "tzdata==2025.2",
    "webencodings==0.5.1",
    "whitenoise==6.9.0",
]

[tool.uv]
# UV-specific configuration
pip = { upgrade = true }

[tool.setuptools]
packages = ["main", "personal_portfolio", "entrypoints"]
