# Generated by Django 5.1.7 on 2025-04-09 20:47

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_short_description_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
