# Generated by Django 5.1.7 on 2025-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250825_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_url',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
