# Generated by Django 5.1.7 on 2026-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_blog_url_optional_unique_when_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_url',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
