# Generated by Django 5.1.7 on 2026-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_markdown_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_libraries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
