# Generated by Django 5.1.7 on 2026-02-19 09:11

from django.db import migrations, models


def seed_portfolio_profile(apps, schema_editor):
    PortfolioProfile = apps.get_model("main", "PortfolioProfile")
    if PortfolioProfile.objects.filter(is_active=True).exists():
        return

    PortfolioProfile.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_markdown_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Portfolio', max_length=100)),
                ('full_name', models.CharField(default='John Doe', max_length=120)),
                ('role_line', models.CharField(default='Junior Full-Stack Developer & Data Science enthusiast', max_length=160)),
                ('specialization_line', models.CharField(default='Specialized in Python, Django, PostgreSQL', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_portfolio_profile')],
            },
        ),
        migrations.RunPython(seed_portfolio_profile, migrations.RunPython.noop),
    ]
