# Generated by Django 5.1.7 on 2026-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_portfolioprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioprofile',
            name='email',
            field=models.EmailField(blank=True, default='example@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/your-username'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/your-profile/'),
        ),
    ]
