# Generated by Django 5.1.7 on 2026-02-19 09:27

from django.db import migrations


def backfill_portfolio_profile_defaults(apps, schema_editor):
    PortfolioProfile = apps.get_model("main", "PortfolioProfile")

    default_email = "example@mail.com"
    default_github = "https://github.com/your-username"
    default_linkedin = "https://www.linkedin.com/in/your-profile/"

    for profile in PortfolioProfile.objects.all():
        changed_fields = []

        if not profile.email:
            profile.email = default_email
            changed_fields.append("email")
        if not profile.github_url:
            profile.github_url = default_github
            changed_fields.append("github_url")
        if not profile.linkedin_url:
            profile.linkedin_url = default_linkedin
            changed_fields.append("linkedin_url")

        if changed_fields:
            profile.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_portfolioprofile_email_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_portfolio_profile_defaults,
            migrations.RunPython.noop,
        ),
    ]
