# Generated by Django 5.1.7 on 2026-02-19 09:56

import django.core.validators
from django.core.files.base import ContentFile
from django.db import migrations, models


def copy_markdown_content_to_files(apps, schema_editor):
    Project = apps.get_model("main", "Project")

    for project in Project.objects.all():
        markdown_content = (project.markdown_content or "").strip()
        if not markdown_content or project.markdown_file:
            continue

        filename = f"{project.blog_url or f'project-{project.id}'}.md"
        project.markdown_file.save(
            filename,
            ContentFile(markdown_content.encode("utf-8")),
            save=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_backfill_portfolio_profile_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='markdown_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_markdown/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])]),
        ),
        migrations.RunPython(copy_markdown_content_to_files, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='markdown_content',
        ),
    ]
