# Generated by Django 5.1.7 on 2026-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_project_markdown_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecutionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=150, unique=True)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failure", "Failure")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
        ),
    ]
