# Generated by Django 5.1.7 on 2026-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_taskexecutionstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecutionstatus",
            name="last_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("partial_success", "Partial success"),
                    ("failure", "Failure"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskexecutionstatus",
            name="last_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskexecutionstatus",
            name="last_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskexecutionstatus",
            name="last_updated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
