# Generated by Django 5.1.7 on 2026-02-19

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_taskexecutionstatus_partial_success_and_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                validators=[main.validators.validate_github_repo_url],
            ),
        ),
    ]
