# Generated by Django 5.1.7 on 2026-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_portfolioprofile_home_intro_and_about_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='portfolio', max_length=40, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('weeks_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
