# Generated by Django 5.1.7 on 2026-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_heatmapsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=150)),
                ('last_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial_success', 'Partial success'), ('failure', 'Failure')], default='', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_total', models.PositiveIntegerField(default=0)),
                ('last_updated', models.PositiveIntegerField(default=0)),
                ('last_failed', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
