# Generated by Django 5.1.7 on 2026-02-21 19:54

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_taskexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprofile',
            name='core_stack',
            field=models.JSONField(blank=True, default=main.models.default_core_stack),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='current_learning',
            field=models.JSONField(blank=True, default=main.models.default_current_learning),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='current_learning_summary',
            field=models.CharField(default='I am expanding my stack to design more scalable systems and improve deployment workflows.', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='interests',
            field=models.JSONField(blank=True, default=main.models.default_interests),
        ),
    ]
