# Generated by Django 5.1.7 on 2025-04-27 16:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
