# Generated by Django 5.1.7 on 2025-04-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_challenges_project_features_project_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
    ]
