# Generated by Django 5.1.7 on 2025-04-29 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Cechy produktu'),
        ),
    ]
