# Generated by Django 5.1.7 on 2025-04-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
    ]
