# Generated by Django 5.1.7 on 2025-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
