# Generated by Django 5.1.7 on 2025-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
