# Generated by Django 5.1.7 on 2025-05-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
