# Generated by Django 5.1.7 on 2025-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
