# Generated by Django 5.1.7 on 2025-05-08 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technical_details',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
        migrations.AlterField(
            model_name='project',
            name='blog',
            field=models.BooleanField(default=True),
        ),
    ]
