# Generated by Django 5.1.7 on 2025-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_project_challenges_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
