name: Build, Push and Deploy

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  # The name for the Docker image, built from the repository name
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This step creates a temporary .env file to be used during the build process.
      - name: Create .env file for build
        run: |
          cat <<EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=${{ vars.DEBUG }}
          ALLOWED_HOSTS=${{ vars.ALLOWED_HOSTS }}
          DOCKER_DB_ENGINE=${{ vars.DOCKER_DB_ENGINE }}
          DOCKER_DB_NAME=${{ vars.DOCKER_DB_NAME }}
          DOCKER_DB_USER=${{ vars.DOCKER_DB_USER }}
          DOCKER_DB_PASSWORD=${{ secrets.DOCKER_DB_PASSWORD }}
          DOCKER_DB_HOST=${{ vars.DOCKER_DB_HOST }}
          DOCKER_DB_PORT=${{ vars.DOCKER_DB_PORT }}
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with Docker Compose
        run: docker compose build

      - name: Push images to GitHub Container Registry
        run: docker compose push

  deploy:
    name: Deploy to EC2
    # This job will only run after 'build-and-push' has succeeded
    needs: build-and-push
    runs-on: ubuntu-latest
    # Run this job only on pushes to the main branch
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to EC2 server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory on the server
            cd /home/ubuntu/my_django_portfolio  
            
            # Pull the latest changes from the main branch of the repository
            git reset --hard origin/main #ALSO RESET, make sure we have pulled code from github
            git pull origin main

            # Log in to GitHub Container Registry on the server
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Set the IMAGE_NAME environment variable
            export IMAGE_NAME=ghcr.io/${{ github.repository }}

            # Pull the latest version of the image from the registry
            docker compose pull

            # Restart the services with the new image
            docker compose up -d --remove-orphans
